<a href="https://colab.research.google.com/github/tawsif113/ml-python-foundations/blob/main/week1/Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS DAY 1

Import Pandas

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
2.0.2

Create Dataframe manually

In [3]:
data = {
    "name": ["John", "Jane", "Bob", "Alice"],
    "age": [25, 30, 35, 40],
    "city": ["New York", "London", "Paris", "Tokyo"],
    "country": ["USA", "UK", "France", "Japan"]
}

df = pd.DataFrame(data)
print(df)

    name  age      city country
0   John   25  New York     USA
1   Jane   30    London      UK
2    Bob   35     Paris  France
3  Alice   40     Tokyo   Japan

Inspect Dataframe

In [4]:
print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df.dtypes)

    name  age      city country
0   John   25  New York     USA
1   Jane   30    London      UK
2    Bob   35     Paris  France
3  Alice   40     Tokyo   Japan
(4, 4)
Index(['name', 'age', 'city', 'country'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      object
 1   age      4 non-null      int64
 2   city     4 non-null      object
 3   country  4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes
None
             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000
name       object
age         int64
city       object
country    object
dtype: object

In [5]:
print(df["name"])
print(df[["name","age"]])

0     John
1     Jane
2      Bob
3    Alice
Name: name, dtype: object
    name  age
0   John   25
1   Jane   30
2    Bob   35
3  Alice   40

Access rows with loc and iloc

In [6]:
print(df.loc[0])
print(df.loc[0,"name"])
print(df.loc[0:2])
print(df.loc[0:2,"name"])

name           John
age              25
city       New York
country         USA
Name: 0, dtype: object
John
   name  age      city country
0  John   25  New York     USA
1  Jane   30    London      UK
2   Bob   35     Paris  France
0    John
1    Jane
2     Bob
Name: name, dtype: object

In [7]:
print(df.iloc[0])
print(df.iloc[0,0])
print(df.iloc[0:2])

name           John
age              25
city       New York
country         USA
Name: 0, dtype: object
John
   name  age      city country
0  John   25  New York     USA
1  Jane   30    London      UK

In [8]:
print(df[df["age"] > 29])

    name  age    city country
1   Jane   30  London      UK
2    Bob   35   Paris  France
3  Alice   40   Tokyo   Japan

Add New Column

In [9]:
df["is_old"] = df["age"] > 30
print(df)

    name  age      city country  is_old
0   John   25  New York     USA   False
1   Jane   30    London      UK   False
2    Bob   35     Paris  France    True
3  Alice   40     Tokyo   Japan    True

Sort Values

In [10]:
print(df.sort_values(by="age",ascending=False))

    name  age      city country  is_old
3  Alice   40     Tokyo   Japan    True
2    Bob   35     Paris  France    True
1   Jane   30    London      UK   False
0   John   25  New York     USA   False

Basic Summary stats

In [11]:
print(df["age"].mean())
print(df["age"].max())
print(df["age"].min())

32.5
40
25

Load A Csv

In [12]:
sample_df = pd.DataFrame({
    "student": ["A", "B", "C", "D"],
    "marks": [80, 75, 90, 85],
    "city": ["Dhaka", "Chattogram", "Dhaka", "Khulna"]
})

sample_df.to_csv("students.csv", index=False)

In [13]:
loaded_df = pd.read_csv("/content/students.csv")
print(loaded_df)

  student  marks        city
0       A     80       Dhaka
1       B     75  Chattogram
2       C     90       Dhaka
3       D     85      Khulna

Practice Tasks

In [14]:
data = {
    "name": ["John", "Jane", "Bob", "Alice"],
    "age": [25, 30, 35, 40],
    "salary": [50000, 60000, 70000, 80000]
}

df = pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns.tolist())

    name  age  salary
0   John   25   50000
1   Jane   30   60000
2    Bob   35   70000
3  Alice   40   80000
(4, 3)
['name', 'age', 'salary']

In [15]:
print(df["name"])

0     John
1     Jane
2      Bob
3    Alice
Name: name, dtype: object

In [16]:
print(df[["name","salary"]])

    name  salary
0   John   50000
1   Jane   60000
2    Bob   70000
3  Alice   80000

In [17]:
print(df[df['age'] > 25])

    name  age  salary
1   Jane   30   60000
2    Bob   35   70000
3  Alice   40   80000

In [18]:
print(df[df['salary'] > 30000])
print(df[(df["age"] > 25) & (df["salary"] > 30000)])

    name  age  salary
0   John   25   50000
1   Jane   30   60000
2    Bob   35   70000
3  Alice   40   80000
    name  age  salary
1   Jane   30   60000
2    Bob   35   70000
3  Alice   40   80000

In [19]:
df['salary_after_bonus'] = df['salary'] + 5000
print(df)

    name  age  salary  salary_after_bonus
0   John   25   50000               55000
1   Jane   30   60000               65000
2    Bob   35   70000               75000
3  Alice   40   80000               85000

In [20]:
print(df.sort_values(by='salary', ascending=False))

    name  age  salary  salary_after_bonus
3  Alice   40   80000               85000
2    Bob   35   70000               75000
1   Jane   30   60000               65000
0   John   25   50000               55000

In [21]:
missing_df = pd.DataFrame({
    "name": ["John", "Jane", None, "Alice"],
    "age": [25, 30, np.nan, 40]
})
print(missing_df)
print(missing_df.isnull())
print(missing_df.isnull().sum())
print(missing_df.isnull().any())

    name   age
0   John  25.0
1   Jane  30.0
2   None   NaN
3  Alice  40.0
    name    age
0  False  False
1  False  False
2   True   True
3  False  False
name    1
age     1
dtype: int64
name    True
age     True
dtype: bool

#PANDAS DAY 2

In [22]:
import pandas as pd
import numpy as np

In [23]:
employee_data = {
    "name": ["Arima", "Rahim", "Karim", "Jannat", "Sadia", "Nabil"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE", "EEE"],
    "city": ["Dhaka", "Dhaka", "Khulna", "Dhaka", "Chattogram", "Khulna"],
    "salary": [50000, 45000, 60000, 40000, 55000, 47000]
}

employees_df = pd.DataFrame(employee_data)
print(employees_df)

     name department        city  salary
0   Arima        CSE       Dhaka   50000
1   Rahim        EEE       Dhaka   45000
2   Karim        CSE      Khulna   60000
3  Jannat        BBA       Dhaka   40000
4   Sadia        CSE  Chattogram   55000
5   Nabil        EEE      Khulna   47000

In [24]:
print(employees_df["department"].value_counts())
print(employees_df["city"].value_counts())

department
CSE    3
EEE    2
BBA    1
Name: count, dtype: int64
city
Dhaka         3
Khulna        2
Chattogram    1
Name: count, dtype: int64

In [25]:
print(employees_df["department"].unique())
print(employees_df["department"].nunique())
print(employees_df["city"].unique())

['CSE' 'EEE' 'BBA']
3
['Dhaka' 'Khulna' 'Chattogram']

Group By Basics

In [29]:
print(employees_df.groupby("department")["salary"].mean())
print(employees_df.groupby("department")["salary"].max())
print(employees_df.groupby("city")["salary"].mean())

department
BBA    40000.0
CSE    55000.0
EEE    46000.0
Name: salary, dtype: float64
department
BBA    40000
CSE    60000
EEE    47000
Name: salary, dtype: int64
city
Chattogram    55000.0
Dhaka         45000.0
Khulna        53500.0
Name: salary, dtype: float64

In [31]:
print(
    employees_df.groupby("department")["salary"].agg(["mean", "max", "min", "count"])
)

               mean    max    min  count
department
BBA         40000.0  40000  40000      1
CSE         55000.0  60000  50000      3
EEE         46000.0  47000  45000      2
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7e262efa3200>

In [32]:
employees_df.groupby(["department", "city"])["salary"].mean()

department  city
BBA         Dhaka         40000.0
CSE         Chattogram    55000.0
            Dhaka         50000.0
            Khulna        60000.0
EEE         Dhaka         45000.0
            Khulna        47000.0
Name: salary, dtype: float64

In [35]:
employees_df.groupby("department").agg(
    {
        "salary":["mean", "count"]
    }
)

             salary
               mean count
department
BBA         40000.0     1
CSE         55000.0     3
EEE         46000.0     2

Transform

In [36]:
employees_df["DeptMean"] = employees_df.groupby("department")["salary"].transform("mean")
print(employees_df)

     name department        city  salary  DeptMean
0   Arima        CSE       Dhaka   50000   55000.0
1   Rahim        EEE       Dhaka   45000   46000.0
2   Karim        CSE      Khulna   60000   55000.0
3  Jannat        BBA       Dhaka   40000   40000.0
4   Sadia        CSE  Chattogram   55000   55000.0
5   Nabil        EEE      Khulna   47000   46000.0

Sort Grouped Result

In [37]:
department_salary = employees_df.groupby("department")["salary"].mean()
print(department_salary.sort_values(ascending=False))

department
CSE    55000.0
EEE    46000.0
BBA    40000.0
Name: salary, dtype: float64

Missing value handling

In [38]:
messy_data = {
    "name": ["John", "Jane", None, "Alice", "Bob"],
    "age": [25, np.nan, 29, 31, None],
    "department": ["CSE", "EEE", "CSE", None, "BBA"],
    "salary": [50000, 60000, None, 55000, 48000]
}

messy_df = pd.DataFrame(messy_data)
print(messy_df)

    name   age department   salary
0   John  25.0        CSE  50000.0
1   Jane   NaN        EEE  60000.0
2   None  29.0        CSE      NaN
3  Alice  31.0       None  55000.0
4    Bob   NaN        BBA  48000.0

In [39]:
print(messy_df.isnull())
print(messy_df.isnull().sum())
print(messy_df.isnull().any())

    name    age  department  salary
0  False  False       False   False
1  False   True       False   False
2   True  False       False    True
3  False  False        True   False
4  False   True       False   False
name          1
age           2
department    1
salary        1
dtype: int64
name          True
age           True
department    True
salary        True
dtype: bool

Fill Missing Values

In [42]:
messy_df["age"] = messy_df["age"].fillna(messy_df["age"].mean())
messy_df
messy_df["salary"] = messy_df["salary"].fillna(messy_df["salary"].mean())
messy_df

    name        age department   salary
0   John  25.000000        CSE  50000.0
1   Jane  28.333333        EEE  60000.0
2   None  29.000000        CSE  53250.0
3  Alice  31.000000       None  55000.0
4    Bob  28.333333        BBA  48000.0

In [43]:
messy_df["name"] = messy_df["name"].fillna("Unknown")
messy_df["department"] = messy_df["department"].fillna("Not Assigned")

In [44]:
print(messy_df)

      name        age    department   salary
0     John  25.000000           CSE  50000.0
1     Jane  28.333333           EEE  60000.0
2  Unknown  29.000000           CSE  53250.0
3    Alice  31.000000  Not Assigned  55000.0
4      Bob  28.333333           BBA  48000.0

In [45]:
messy_df2 = pd.DataFrame(messy_data)

print(messy_df2.dropna())

   name   age department   salary
0  John  25.0        CSE  50000.0

In [46]:
print(messy_df2.dropna(axis=1))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [47]:
print(employees_df.rename(columns={"salary": "monthly_salary"}))

     name department        city  monthly_salary  DeptMean
0   Arima        CSE       Dhaka           50000   55000.0
1   Rahim        EEE       Dhaka           45000   46000.0
2   Karim        CSE      Khulna           60000   55000.0
3  Jannat        BBA       Dhaka           40000   40000.0
4   Sadia        CSE  Chattogram           55000   55000.0
5   Nabil        EEE      Khulna           47000   46000.0

In [48]:
print(employees_df.drop(columns=["city"]))

     name department  salary  DeptMean
0   Arima        CSE   50000   55000.0
1   Rahim        EEE   45000   46000.0
2   Karim        CSE   60000   55000.0
3  Jannat        BBA   40000   40000.0
4   Sadia        CSE   55000   55000.0
5   Nabil        EEE   47000   46000.0

In [49]:
print(employees_df.drop(index=[0]))

     name department        city  salary  DeptMean
1   Rahim        EEE       Dhaka   45000   46000.0
2   Karim        CSE      Khulna   60000   55000.0
3  Jannat        BBA       Dhaka   40000   40000.0
4   Sadia        CSE  Chattogram   55000   55000.0
5   Nabil        EEE      Khulna   47000   46000.0

Practice

In [51]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "department": ["HR", "IT", "Finance", "IT", "HR", "Finance"],
    "city": ["Dhaka", "Chattogram", "Dhaka", "Khulna", "Dhaka", "Rajshahi"],
    "salary": [50000, 70000, 65000, 72000, 52000, 68000]
})

print("Original DataFrame:")
print(df)

Original DataFrame:
      name department        city  salary
0    Alice         HR       Dhaka   50000
1      Bob         IT  Chattogram   70000
2  Charlie    Finance       Dhaka   65000
3    David         IT      Khulna   72000
4      Eva         HR       Dhaka   52000
5    Frank    Finance    Rajshahi   68000

In [52]:
print("\ndepartment.value_counts():")
print(df["department"].value_counts())

print("\ncity.value_counts():")
print(df["city"].value_counts())

department.value_counts():
department
HR         2
IT         2
Finance    2
Name: count, dtype: int64

city.value_counts():
city
Dhaka         3
Chattogram    1
Khulna        1
Rajshahi      1
Name: count, dtype: int64

In [53]:
print("Unique departments:")
print(df["department"].unique())

print("\nNumber of unique cities:")
print(df["city"].nunique())

Unique departments:
['HR' 'IT' 'Finance']

Number of unique cities:
4

In [54]:
grouped = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    maximum_salary=("salary", "max"),
    employee_count=("name", "count")
)

print("Grouped by department:")
print(grouped)

Grouped by department:
            average_salary  maximum_salary  employee_count
department
Finance            66500.0           68000               2
HR                 51000.0           52000               2
IT                 71000.0           72000               2

In [55]:
grouped = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    maximum_salary=("salary", "max"),
    employee_count=("name", "count")
).round(2)

print(grouped)

            average_salary  maximum_salary  employee_count
department
Finance            66500.0           68000               2
HR                 51000.0           52000               2
IT                 71000.0           72000               2

In [56]:
messy_df = pd.DataFrame({
    "name": ["Alice", None, "Charlie", "David", None, "Frank"],
    "age": [25, 30, None, 28, 35, None],
    "salary": [50000, None, 65000, None, 52000, 68000]
})

print("Messy DataFrame:")
print(messy_df)

Messy DataFrame:
      name   age   salary
0    Alice  25.0  50000.0
1     None  30.0      NaN
2  Charlie   NaN  65000.0
3    David  28.0      NaN
4     None  35.0  52000.0
5    Frank   NaN  68000.0

In [57]:
print("\nisnull():")
print(messy_df.isnull())

print("\nisnull().sum():")
print(messy_df.isnull().sum())

print("\nisnull().any():")
print(messy_df.isnull().any())

isnull():
    name    age  salary
0  False  False   False
1   True  False    True
2  False   True   False
3  False  False    True
4   True  False   False
5  False   True   False

isnull().sum():
name      2
age       2
salary    2
dtype: int64

isnull().any():
name      True
age       True
salary    True
dtype: bool

In [58]:
filled_df = messy_df.copy()

filled_df["name"] = filled_df["name"].fillna("Unknown")
filled_df["age"] = filled_df["age"].fillna(filled_df["age"].mean())
filled_df["salary"] = filled_df["salary"].fillna(filled_df["salary"].median())

print("DataFrame after filling missing values:")
print(filled_df)

DataFrame after filling missing values:
      name   age   salary
0    Alice  25.0  50000.0
1  Unknown  30.0  58500.0
2  Charlie  29.5  65000.0
3    David  28.0  58500.0
4  Unknown  35.0  52000.0
5    Frank  29.5  68000.0

In [59]:
filled_df["age"] = filled_df["age"].round().astype(int)
print(filled_df)

      name  age   salary
0    Alice   25  50000.0
1  Unknown   30  58500.0
2  Charlie   30  65000.0
3    David   28  58500.0
4  Unknown   35  52000.0
5    Frank   30  68000.0

In [60]:
updated_df = df.rename(columns={"salary": "monthly_salary"}).drop(columns=["city"])

print("Updated DataFrame:")
print(updated_df)

Updated DataFrame:
      name department  monthly_salary
0    Alice         HR           50000
1      Bob         IT           70000
2  Charlie    Finance           65000
3    David         IT           72000
4      Eva         HR           52000
5    Frank    Finance           68000

##My understanding
1. What value_counts() does

value_counts() counts how many times each unique value appears in a column.

Example:
If the department column has HR, IT, HR, Finance, then value_counts() will tell us:

HR → 2

IT → 1

Finance → 1

It is useful when we want to quickly see the frequency of categories.

2. What groupby() does

groupby() groups rows that have the same value in a selected column, then lets us perform calculations on each group.

Example:
If we group by department, then all HR employees go together, all IT employees go together, and so on.
After that, we can calculate:

average salary

max salary

employee count

So groupby() is useful for summarizing data by category.

3. Difference between fillna() and dropna()

fillna() is used to replace missing values with something else.

Example:

missing name → "Unknown"

missing age → average age

dropna() is used to remove rows or columns that contain missing values.

So:

fillna() keeps the data and fills the gaps

dropna() removes incomplete data

4. When unique() is useful

unique() is useful when we want to know all distinct values in a column.

Example:
If the city column has Dhaka, Dhaka, Khulna, Rajshahi, then unique() gives:
['Dhaka', 'Khulna', 'Rajshahi']

It helps us understand what different categories exist in the data.